---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{{name}}}
spec:
  replicas: {{{replicas}}}
  selector:
    matchLabels:
      name: {{{name}}}
  template:
    metadata:
      labels:
        name: {{{name}}}
        service: {{{name}}}
    spec:
      containers:
        - name: app
          image: {{{image}}}
          imagePullPolicy: Always
          {{#env.length}}
          env:
            {{#env}}
            - name: {{{name}}}
              {{^secret}}
              value: {{{value}}}
              {{/secret}}
              {{#secret}}
              valueFrom:
                secretKeyRef:
                  name: {{{secret}}}
                  key: {{{key}}}
              {{/secret}}
            {{/env}}
          {{/env.length}}
          resources:
            limits:
              memory: {{{memory.limit}}}
              cpu: {{{cpu.limit}}}
            requests:
              memory: {{{memory.requests}}}
              cpu: {{{cpu.requests}}}
          securityContext:
            runAsNonRoot: true
