---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{{name}}}
spec:
  schedule: "{{{schedule}}}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: app
              image: {{{image}}}
              command: {{{command}}}
              {{#env.length}}
              env:
                {{#env}}
                - name: {{{name}}}
                  {{^secret}}
                  value: {{{value}}}
                  {{/secret}}
                  {{#secret}}
                  valueFrom:
                    secretKeyRef:
                      name: {{{secret}}}
                      key: {{{key}}}
                  {{/secret}}
                {{/env}}
              {{/env.length}}
              resources:
                limits:
                  memory: {{{memory.limit}}}
                  cpu: {{{cpu.limit}}}
                requests:
                  memory: {{{memory.requests}}}
                  cpu: {{{cpu.requests}}}
              securityContext:
                runAsNonRoot: true
