---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{{name}}}
    service: {{{name}}}
  name: {{{name}}}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: {{{name}}}
