---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{{name}}}-
spec:
  template:
    spec:
      completions: 1
      restartPolicy: Never
      containers:
        - name: app
          image: {{{image}}}
          imagePullPolicy: Always
          command: {{{command}}}
          {{#env.length}}
          env:
            {{#env}}
            - name: {{{name}}}
              {{^secret}}
              value: {{{value}}}
              {{/secret}}
              {{#secret}}
              valueFrom:
                secretKeyRef:
                  name: {{{secret}}}
                  key: {{{key}}}
              {{/secret}}
            {{/env}}
          {{/env.length}}
          resources:
            limits:
              memory: {{{memory.limit}}}
              cpu: {{{cpu.limit}}}
            requests:
              memory: {{{memory.requests}}}
              cpu: {{{cpu.requests}}}
          securityContext:
            runAsNonRoot: true
