---
apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: {{{name}}}
spec:
  containers:
    - name: app
      image: {{{image}}}
      imagePullPolicy: Always
      {{#env.length}}
      env:
        {{#env}}
        - name: {{{name}}}
          {{^secret}}
          value: {{{value}}}
          {{/secret}}
          {{#secret}}
          valueFrom:
            secretKeyRef:
              name: {{{secret}}}
              key: {{{key}}}
          {{/secret}}
        {{/env}}
      {{/env.length}}
      readinessProbe:
        exec:
          command:
          - cat
          - {{{ready}}}
      livenessProbe:
        exec:
          command:
          - cat
          - {{{alive}}}
      securityContext:
        runAsNonRoot: true
