---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{{name}}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{{name}}}
        service: {{{name}}}
    spec:
      containers:
        - name: app
          image: {{{image}}}
          imagePullPolicy: Always
          {{#env.length}}
          env:
            {{#env}}
            - name: {{{name}}}
              {{^secret}}
              value: {{{value}}}
              {{/secret}}
              {{#secret}}
              valueFrom:
                secretKeyRef:
                  name: {{{secret}}}
                  key: {{{key}}}
              {{/secret}}
            {{/env}}
          {{/env.length}}
          readinessProbe:
            exec:
              command:
              - cat
              - {{{ready}}}
              initialDelaySeconds: 10
          livenessProbe:
            exec:
              command:
              - cat
              - {{{alive}}}
              initialDelaySeconds: 20
          resources:
            limits:
              memory: {{{memory}}}
          securityContext:
            runAsNonRoot: true
