---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{{name}}}
spec:
  maxReplicas: {{max}}
  minReplicas: {{min}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{{name}}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{utilisation}}
