---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{{name}}}
spec:
  replicas: {{{replicas}}}
  template:
    metadata:
      labels:
        name: {{{name}}}
        service: {{{name}}}
    spec:
      containers:
        - name: app
          image: {{{image}}}
          imagePullPolicy: Always
          {{#env.length}}
          env:
            {{#env}}
            - name: {{{name}}}
              {{^secret}}
              value: {{{value}}}
              {{/secret}}
              {{#secret}}
              valueFrom:
                secretKeyRef:
                  name: {{{secret}}}
                  key: {{{key}}}
              {{/secret}}
            {{/env}}
          {{/env.length}}
          resources:
            limits:
              memory: {{{memory}}}
          securityContext:
            runAsNonRoot: true
        - name: nginx-proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy-govuk:v3
          {{#nginx.length}}
          env:
            {{#nginx}}
            - name: {{{name}}}
              {{^secret}}
              value: {{{value}}}
              {{/secret}}
              {{#secret}}
              valueFrom:
                secretKeyRef:
                  name: {{{secret}}}
                  key: {{{key}}}
              {{/secret}}
            {{/nginx}}
          {{/nginx.length}}
          ports:
            - containerPort: 10443
          securityContext:
            runAsNonRoot: true
