---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{{name}}}
spec:
  replicas: {{{replicas}}}
  selector:
    matchLabels:
      name: {{{name}}}
  template:
    metadata:
      labels:
        name: {{{name}}}
        service: {{{name}}}
    spec:
      {{#keys}}
      volumes:
        - name: keys
          secret:
            secretName: {{{keys}}}
      {{/keys}}
      containers:
        - name: app
          image: {{{image}}}
          imagePullPolicy: Always
          {{#env.length}}
          env:
            {{#env}}
            - name: {{{name}}}
              {{^secret}}
              value: {{{value}}}
              {{/secret}}
              {{#secret}}
              valueFrom:
                secretKeyRef:
                  name: {{{secret}}}
                  key: {{{key}}}
              {{/secret}}
            {{/env}}
          {{/env.length}}
          resources:
            limits:
              memory: {{{memory.limit}}}
              cpu: {{{cpu.limit}}}
            requests:
              memory: {{{memory.requests}}}
              cpu: {{{cpu.requests}}}
          securityContext:
            runAsNonRoot: true
          {{#healthcheck}}
          livenessProbe:
            httpGet:
              path: {{healthcheck}}
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: {{healthcheck}}
              port: 8080
            timeoutSeconds: 1
          {{/healthcheck}}
        - name: nginx-proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy:v3
          imagePullPolicy: Always
          {{#nginx.length}}
          env:
            {{#nginx}}
            - name: {{{name}}}
              {{^secret}}
              value: {{{value}}}
              {{/secret}}
              {{#secret}}
              valueFrom:
                secretKeyRef:
                  name: {{{secret}}}
                  key: {{{key}}}
              {{/secret}}
            {{/nginx}}
          {{/nginx.length}}
          ports:
            - containerPort: 10443
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: 32Mi
              cpu: 20m
          {{#keys}}
          volumeMounts:
            - name: keys
              mountPath: "/etc/keys"
          {{/keys}}
