---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{{name}}}-permit-access
spec:
  ingress:
  - from:
    {{#clients}}
    - podSelector:
        matchLabels:
          name: {{{.}}}
    {{/clients}}
    ports:
    - port: 10443
      protocol: TCP
  podSelector:
    matchLabels:
      name: {{{name}}}
