---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{{name}}}
spec:
  replicas: {{{replicas}}}
  selector:
    matchLabels:
      name: {{{name}}}
  template:
    metadata:
      labels:
        name: {{{name}}}
        service: {{{name}}}
    spec:
      containers:
        - name: app
          image: {{{image}}}
          {{#env.length}}
          env:
            {{#env}}
            - name: {{{name}}}
              {{^secret}}
              value: {{{value}}}
              {{/secret}}
              {{#secret}}
              valueFrom:
                secretKeyRef:
                  name: {{{secret}}}
                  key: {{{key}}}
              {{/secret}}
            {{/env}}
          {{/env.length}}
          resources:
            limits:
              memory: {{{memory.limit}}}
              cpu: {{{cpu.limit}}}
            requests:
              memory: {{{memory.requests}}}
              cpu: {{{cpu.requests}}}
          securityContext:
            runAsNonRoot: true
          {{#healthcheck}}
          livenessProbe:
            httpGet:
              path: {{healthcheck}}
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: {{healthcheck}}
              port: 8080
            timeoutSeconds: 1
          {{/healthcheck}}
        - name: nginx-proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy:v3
          {{#nginx.length}}
          env:
            {{#maxBodySize}}
            - name: CLIENT_MAX_BODY_SIZE
              value: '{{{maxBodySize}}}'
            {{/maxBodySize}}
            {{#nginx}}
            - name: {{{name}}}
              {{^secret}}
              value: {{{value}}}
              {{/secret}}
              {{#secret}}
              valueFrom:
                secretKeyRef:
                  name: {{{secret}}}
                  key: {{{key}}}
              {{/secret}}
            {{/nginx}}
          {{/nginx.length}}
          ports:
            - containerPort: 10443
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: 32Mi
              cpu: 100m
