---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{{name}}}-ingress
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{#internal}}
    kubernetes.io/ingress.class: "nginx-internal"
    {{/internal}}
    {{^internal}}
    kubernetes.io/ingress.class: "nginx-external"
    stable.k8s.psg.io/kcm.provider: http
    {{/internal}}
    {{#whitelist}}
    ingress.kubernetes.io/whitelist-source-range: {{{whitelist}}}
    {{/whitelist}}
  labels:
    stable.k8s.psg.io/kcm.class: "default"
spec:
  tls:
  - hosts:
    - {{{url}}}
    secretName: {{{name}}}-cert
  rules:
  - host: {{{url}}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{{name}}}
          servicePort: 10443
