---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{{name}}}-ingress
  annotations:
    ingress.kubernetes.io/proxy-body-size: "{{{maxBodySize}}}m"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/enabled: "true"
    {{#internal}}
    kubernetes.io/ingress.class: "nginx-internal"
    {{/internal}}
    {{^internal}}
    kubernetes.io/ingress.class: "nginx-external"
    {{/internal}}
    {{#whitelist}}
    ingress.kubernetes.io/whitelist-source-range: {{{whitelist}}}
    {{/whitelist}}
  labels:
    cert-manager.io/solver: http01
spec:
{{#internal}}
  ingressClassName: ingress-internal
{{/internal}}
{{^internal}}
  ingressClassName: ingress-external
{{/internal}}
  tls:
  - hosts:
    - {{{url}}}
    secretName: {{{name}}}-cert-cmio
  rules:
  - host: {{{url}}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{{name}}}
          servicePort: 10443
