---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{{name}}}-allow-ingress
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{#internal}}
          name: ingress-internal
          {{/internal}}
          {{^internal}}
          name: ingress-external
          {{/internal}}
    ports:
    - port: 10080
      protocol: TCP
    - port: 10443
      protocol: TCP
  podSelector:
    matchLabels:
      name: {{{name}}}
  policyTypes:
  - Ingress